// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/indusrtial-calculator.proto

package industrial_calculator_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndustrialCalculator_Process_FullMethodName = "/api.IndustrialCalculator/Process"
)

// IndustrialCalculatorClient is the client API for IndustrialCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndustrialCalculatorClient interface {
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
}

type industrialCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewIndustrialCalculatorClient(cc grpc.ClientConnInterface) IndustrialCalculatorClient {
	return &industrialCalculatorClient{cc}
}

func (c *industrialCalculatorClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, IndustrialCalculator_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndustrialCalculatorServer is the server API for IndustrialCalculator service.
// All implementations must embed UnimplementedIndustrialCalculatorServer
// for forward compatibility.
type IndustrialCalculatorServer interface {
	Process(context.Context, *ProcessRequest) (*ProcessResponse, error)
	mustEmbedUnimplementedIndustrialCalculatorServer()
}

// UnimplementedIndustrialCalculatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndustrialCalculatorServer struct{}

func (UnimplementedIndustrialCalculatorServer) Process(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedIndustrialCalculatorServer) mustEmbedUnimplementedIndustrialCalculatorServer() {}
func (UnimplementedIndustrialCalculatorServer) testEmbeddedByValue()                              {}

// UnsafeIndustrialCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndustrialCalculatorServer will
// result in compilation errors.
type UnsafeIndustrialCalculatorServer interface {
	mustEmbedUnimplementedIndustrialCalculatorServer()
}

func RegisterIndustrialCalculatorServer(s grpc.ServiceRegistrar, srv IndustrialCalculatorServer) {
	// If the following call pancis, it indicates UnimplementedIndustrialCalculatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndustrialCalculator_ServiceDesc, srv)
}

func _IndustrialCalculator_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndustrialCalculatorServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndustrialCalculator_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndustrialCalculatorServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndustrialCalculator_ServiceDesc is the grpc.ServiceDesc for IndustrialCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndustrialCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.IndustrialCalculator",
	HandlerType: (*IndustrialCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _IndustrialCalculator_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/indusrtial-calculator.proto",
}
